# Project information
site_name: "Uganda EMR Technical Guide"
site_description: "Technical documentation for Uganda EMR"
site_author: "METS Programme"
site_url: "https://github.com/METS-Programme/ugandaemr-technicalguide/" 
site_dir: "root"

# Repository
repo_name: "ugandaemr-technicalguide"
repo_url: "https://github.com/METS-Programme/ugandaemr-technicalguide"

# Copyright
copyright: "Copyright © 2021 METS Programme"

# Theme
theme:
  name: "material"
  palette:
    primary: "blue grey"
    accent: "indigo"
  language: "en"
  font:
    text: "Roboto"
    code: "Roboto Mono"
  features:
    # - navigation.expand
    - navigation.tabs

nav:
  - Home:
    - 'SUMMARY.md'
 
