# Project information
site_name: "Uganda EMR Technical Guide"
site_description: "Technical documentation for Uganda EMR"
site_author: "METS"
site_url: "https://github.com/intrahealth/client-registry"

# Repository
repo_name: "ugandaemr-technicalguide"
repo_url: "https://austinbwanika.github.io/ugandaemr-technicalguide/"

# Copyright
copyright: "Copyright &copy; 2021 Uganda EMR"

# Theme
theme:
  name: "material"
  palette:
    primary: "blue grey"
    accent: "indigo"
  language: "en"
  font:
    text: "Roboto"
    code: "Roboto Mono"
  features:
    # - navigation.expand
    - navigation.tabs

nav:
  - Home:
    - 'SUMMARY.md'
 
